name: Sync error metadata
on:
  schedule:
    - cron: '0 16 * * *' # Every day at 0:00 (UTC+8)

concurrency: repo_sync

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Generate app token for bot
      uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.BOT_APP_ID }}
        private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ steps.generate-token.outputs.token }}

    - name: Fetch error metadata (zh-CN)
      working-directory: ./zh-CN
      run: wget https://main.qcloudimg.com/qcloud/main/scripts/release/common/api-all-errorcodes.json -O error-codes.json

    - name: Import bot's GPG key for signing commits
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        author_name: ${{ steps.import-gpg.outputs.name }}
        author_email: ${{ steps.import-gpg.outputs.email }}
        message: 'Update error metadata'
        push: true
